version: '3'
services:
  node-app:
    build: .
    working_dir: /app
    ports:
      - "3000:3000"
    depends_on:
      - phpmyadmin

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpole
      MYSQL_DATABASE: pole
      MYSQL_USER: rootkhalid
      MYSQL_PASSWORD: rootkhalid
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: rootpole
      MYSQL_USER: rootkhalid
      MYSQL_PASSWORD: rootkhalid
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  mysql-data:
